# Generated by Django 2.2.4 on 2019-08-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='categoria',
            field=models.TextField(max_length=30, verbose_name='categoria'),
        ),
    ]
