# Generated by Django 2.2.4 on 2019-08-07 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_auto_20190806_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
