# Generated by Django 2.2.4 on 2019-08-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_auto_20190806_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='categorias',
            field=models.TextField(max_length=30, verbose_name='categorias'),
        ),
    ]
